version: '3'

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: merkur-front
    command: yarn dev
    environment:
      - NEXT_PUBLIC_API_URL='http://165.227.214.134/api'
    volumes:
      - .:/home/node/front
      - /home/node/front/node_modules
    ports:
      - '3000:3000'
