export { default as Header } from './Header'
export { default as SEO } from './SEO'
export { default as SearchProducts } from './SearchProducts'
export { default as Footer } from './Footer'
export { default as ModalProductDetails } from './ModalProductDetails'
export { default as BuyQuantityInput } from './BuyQuantityInput'
